#Should we charge people to make a faction?
charge-for-faction-creation: true
#How much should we charge them if we are?
creation-price: 100

#Should we use permissions to allow access to player commands?
use-permissions: true

#What should the most power a player can have be?
max-power: 30
#What should the minimum be?
min-power: -30

spawn-enabled: true
spawn-location: nospawn
#How long should we wait before teleporting players to spawn?
spawn-teleport-warmup-time: 5

commands-per-help-page: 8